config/routes.rb
Classroom::Application.routes.draw do

  resources :users
  match '/seatings/index' => 'seatings#index', :as => :seating
  resources :loginseatings do
  	resources :comments
  end
  
  match '/loginseatings/' => 'loginseatings#index', :as => :loginseating
  match '/loginseatings/' => 'loginseatings#select', :as => :select 
 
  
  resources :seatings
  resource :session  

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  
  resources :login
  

  root :to => "seatings#index"
end

app/models/seating.rb
class Seating < ActiveRecord::Base
end

app/controllers/seatings_controller.rb
class SeatingsController < ApplicationController
  # GET /seatings
  # GET /seatings.xml
  def index
    #@seatings = Seating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seatings }
    end
  end

  # GET /seatings/1
  # GET /seatings/1.xml
  def show
    @seating = Seating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @seating }
    end
  end

  # GET /seatings/new
  # GET /seatings/new.xml
  def new
    @seating = Seating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seating }
    end
  end

  # GET /seatings/1/edit
  def edit
    @seating = Seating.find(params[:id])
  end

  # POST /seatings
  # POST /seatings.xml
  def create
    @seating = Seating.new(params[:seating])

    respond_to do |format|
      if @seating.save
        format.html { redirect_to(@seating, :notice => 'Seating was successfully created.') }
        format.xml  { render :xml => @seating, :status => :created, :location => @seating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @seating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /seatings/1
  # PUT /seatings/1.xml
  def update
    @seating = Seating.find(params[:id])

    respond_to do |format|
      if @seating.update_attributes(params[:seating])
        format.html { redirect_to(@seating, :notice => 'Seating was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /seatings/1
  # DELETE /seatings/1.xml
  def destroy
    @seating = Seating.find(params[:id])
    @seating.destroy

    respond_to do |format|
      format.html { redirect_to(seatings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/seatings_helper.rb
module SeatingsHelper
end

app/views/seatings/_form.html.erb
<%= form_for(@seating) do |f| %>
  <% if @seating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seating.errors.count, "error") %> prohibited this seating from being saved:</h2>

      <ul>
      <% @seating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seatings/edit.html.erb
<h1>Editing seating</h1>

<%= render 'form' %>

<%= link_to 'Show', @seating %> |
<%= link_to 'Back', seatings_path %>

app/views/seatings/index.html.erb
<h1>Listing seatings</h1>

<table border cellspacing = "5" width="100%">
<% for i in 1..5 %>
  <tr>
  <% for j in 1..9 %>
	<td>
	<% if j == 5 %>
		BLANK CELL
	<% else %>
		Student <%= i %><%= j %>
	<% end %>
	</td>
  <% end %>
  </tr>
<% end %>

</table>

<%= link_to 'LOGIN', login_path %>

<br />

app/views/seatings/login.html.erb
<html>
<title>LOGIN</title>
<h1>Login></h1>

<%= link_to 'Login Button', seatings_path %> |

</html>

app/views/seatings/new.html.erb
<h1>New seating</h1>

<%= render 'form' %>

<%= link_to 'Back', seatings_path %>

app/views/seatings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_seating_path(@seating) %> |
<%= link_to 'Back', seatings_path %>