config/routes.rb
Classroom::Application.routes.draw do

  resources :users
  match '/seatings/index' => 'seatings#index', :as => :seating
  resources :loginseatings do
  	resources :comments
  end
  
  match '/loginseatings/' => 'loginseatings#index', :as => :loginseating
  match '/loginseatings/' => 'loginseatings#select', :as => :select 
 
  
  resources :seatings
  resource :session  

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  
  resources :login
  

  root :to => "seatings#index"
end

app/models/loginseating.rb
class Loginseating < ActiveRecord::Base
end

app/models/loginseatings.rb
class Loginseatings < ActiveRecord::Base
end

app/controllers/loginseatings_controller.rb
class LoginseatingsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]
  
  # GET /loginseatings
  # GET /loginseatings.xml
  def index
    @loginseating = Loginseating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @loginseatings }
    end
  end

  # GET /loginseatings/1
  # GET /loginseatings/1.xml
  def show
    @loginseating = Loginseating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @loginseating }
    end
  end

  # GET /loginseatings/new
  # GET /loginseatings/new.xml
  def new
    @loginseating = Loginseating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @loginseating }
    end
  end

  # GET /loginseatings/1/edit
  def edit
    @loginseating = Loginseating.find(params[:id])
  end

  # POST /loginseatings
  # POST /loginseatings.xml
  def create
    @loginseating = Loginseating.new(params[:loginseating])

    respond_to do |format|
      if @loginseating.save
        format.html { redirect_to(@loginseating, :notice => 'Loginseating was successfully created.') }
        format.xml  { render :xml => @loginseating, :status => :created, :location => @loginseating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @loginseating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /loginseatings/1
  # PUT /loginseatings/1.xml
  def update
    @loginseating = Loginseating.find(params[:id])

    respond_to do |format|
      if @loginseating.update_attributes(params[:loginseating])
        format.html { redirect_to(@loginseating, :notice => 'Loginseating was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @loginseating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /loginseatings/1
  # DELETE /loginseatings/1.xml
  def destroy
    @loginseating = Loginseating.find(params[:id])
    @loginseating.destroy

    respond_to do |format|
      format.html { redirect_to(loginseatings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/loginseatings_helper.rb
module LoginseatingsHelper
end

app/views/loginseatings/_form.html.erb
<%= form_for(@loginseating) do |f| %>
  <% if @loginseating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loginseating.errors.count, "error") %> prohibited this loginseating from being saved:</h2>

      <ul>
      <% @loginseating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loginseatings/_loginseating.html.erb
<%= div_for loginseating do %>
  <h3>
    <%= link_to loginseating.title, loginseating %>
    <span class='actions'>
      <%= link_to "Edit", edit_loginseating_path(loginseating) %>
      <%= link_to "Delete", loginseating, :confirm => "Are you sure?", :method => :delete %>
    </span>
  </h3>
  <%= loginseating.body %>
<% end %>

app/views/loginseatings/_selectform.html.erb
<%= form_for(@loginseating) do |f| %>
  <% if @loginseating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loginseating.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @loginseating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :studentfirst %><br />
    <%= f.text_field :studentfirst %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loginseatings/edit.html.erb
<h1>Editing loginseating</h1>

<%= render 'form' %>

<%= link_to 'Show', @loginseating %> |
<%= link_to 'Back', loginseatings_path %>

app/views/loginseatings/index.html.erb
<html>
<title>Class Room Seating</title> 
<% user = Users.find(session[:user_id]) %>
<h5>Welcome, <%= user.username %></h5>
<br /> 
<h1>Classroom Seating</h1>  
<table border cellspacing=4 width="100%"> 
<br /><br /> FRONT OF CLASS <br /> 
<% for i in 1..5 %>
 	<tr>
	<% for j in 1..9 %>
	<td>
	<% if j == 5 %>
	BLANK CELL
	<% else %>
	Student <%= i; %> <%= j; %><br /><%= link_to 'Select Seat', :controller => "loginseatings"  %>
	<% end %> 			
	</td> 		
	<% end %> 	
	</tr> 
	<% end %> 
	</table>   
	<br />  
</html>

app/views/loginseatings/new.html.erb
<h1>New loginseating</h1>

<%= render 'form' %>

<%= link_to 'Back', loginseatings_path %>

app/views/loginseatings/select.html.erb
<h1>Seat Chosen</h1><%  %><%= link_to 'Show', @user %> |<%= link_to 'Back', loginseating_path %>

app/views/loginseatings/show.html.erb
<%= render @loginseating %>

<h3>Comments</h3>
<div id="comments">
  <%= render @loginseating.comments %>
</div>

<%= render :file => 'comments/new' %>